name: posts
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.3.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  flutter_spinkit: ^5.2.0
  fluttertoast: ^8.2.2
  get_it: ^7.6.0
  simple_animations: ^4.2.0
  supercharged: ^2.1.1
  shared_preferences: ^2.2.0
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Expo
      fonts:
        - asset: assets/fonts/Expo-Arabic-Bold.ttf
          weight: 700
        - asset: assets/fonts/Expo-Arabic-Medium.ttf
          weight: 500
        - asset: assets/fonts/Expo-Arabic-regular.ttf
          weight: 400
        - asset: assets/fonts/Expo-Arabic-Light.ttf
          weight: 300
